/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * B8boost API
 * OpenAPI spec version: 1.0
 */

export type AiStreamResponseChoicesItem = {
  finish_reason?: string;
  index?: number;
  logprobs?: string;
  stop_reason?: string;
  text?: string;
};
