/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * B8boost API
 * OpenAPI spec version: 1.0
 */
import type { AiStreamResponseChoicesItem } from "./aiStreamResponseChoicesItem";

export interface AiStreamResponse {
  choices?: AiStreamResponseChoicesItem[];
  created?: number;
  id?: string;
  model?: string;
  object?: string;
  usage?: string;
}
