/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * B8boost API
 * OpenAPI spec version: 1.0
 */
import type { EntitiesEvent } from "./entitiesEvent";
import type { EntitiesProduct } from "./entitiesProduct";

export interface EntitiesCompany {
  company?: string;
  companyID?: number;
  description?: string;
  events?: EntitiesEvent[];
  logo?: string;
  products?: EntitiesProduct[];
  title?: string;
}
