/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * B8boost API
 * OpenAPI spec version: 1.0
 */

export interface EntitiesProduct {
  availability?: number;
  caseTypeID?: number;
  companyID?: number;
  description?: string;
  image?: string;
  name?: string;
  price?: number;
  productCategory?: string;
  productID?: number;
}
