/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * B8boost API
 * OpenAPI spec version: 1.0
 */
import type { EntitiesAchievementType } from "./entitiesAchievementType";
import type { EntitiesCompany } from "./entitiesCompany";

export interface EntitiesEvent {
  achievementType?: EntitiesAchievementType;
  achievementTypeID?: number;
  coin?: number;
  company?: EntitiesCompany;
  companyID?: number;
  createdAt?: string;
  description?: string;
  endDs?: string;
  eventID?: number;
  eventName?: string;
  eventType?: string;
  maxUsers?: number;
  startDs?: string;
  status?: string;
  title?: string;
}
