/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * B8boost API
 * OpenAPI spec version: 1.0
 */
import type { EntitiesCompany } from "./entitiesCompany";

export interface EntitiesProduct {
  avalibility?: number;
  company?: EntitiesCompany;
  companyID?: number;
  description?: string;
  image?: string;
  name?: string;
  price?: number;
  productID?: number;
}
