/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * B8boost API
 * OpenAPI spec version: 1.0
 */

export interface EntitiesUserWinning {
  delivered?: boolean;
  deliveredAt?: string;
  deliveredBy?: number;
  productID?: number;
  userID?: number;
  userWinningID?: number;
  winType?: string;
  wonAt?: string;
}
