/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * B8boost API
 * OpenAPI spec version: 1.0
 */

export interface EntitiesUser {
  avatar?: string;
  birthDate?: string;
  companyID?: number;
  createdAt?: string;
  description?: string;
  email?: string;
  isOnline?: boolean;
  lastLogin?: string;
  lastSurname?: string;
  ldapID?: string;
  name?: string;
  phone?: string;
  role?: string;
  surname?: string;
  telegramID?: number;
  updatedAt?: string;
  userID?: number;
}
