/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * B8boost API
 * OpenAPI spec version: 1.0
 */
import type { EntitiesUser } from "./entitiesUser";
import type { EntitiesUserWallet } from "./entitiesUserWallet";

export interface UsecaseTopBalance {
  user?: EntitiesUser;
  wallet?: EntitiesUserWallet;
}
