/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * B8boost API
 * OpenAPI spec version: 1.0
 */
import type { UsecaseEventWithRegistration } from "./usecaseEventWithRegistration";

export interface UsecaseUpcomingEventList {
  events?: UsecaseEventWithRegistration[];
  total?: number;
}
