/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * B8boost API
 * OpenAPI spec version: 1.0
 */

export type UsecaseUpcomingEventInputPeriod =
  (typeof UsecaseUpcomingEventInputPeriod)[keyof typeof UsecaseUpcomingEventInputPeriod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UsecaseUpcomingEventInputPeriod = {
  today: "today",
  tomorrow: "tomorrow",
  week: "week",
  month: "month",
} as const;
