/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * B8boost API
 * OpenAPI spec version: 1.0
 */
import type { EntitiesEvent } from "./entitiesEvent";

export interface UsecaseClosedEventsOutput {
  events?: EntitiesEvent[];
}
